#!/bin/bash

if [ $# -lt 1 ] # if there are fewer than 2 arguments
then
	echo "Please provide 1 .bpl file as commandline argument."
else

	execname=${1%.bpl}
	filename="./"${execname##*/}".s"
  filename2="./"${execname##*/}
	javac -d bin src/*.java
	cd bin
	java BPLCodeGenerator "../"$1 > "../"$filename
	chmod 755 "../"$filename
	gcc -o "../"$filename2 "../"$filename
fi
